doc/team.txt

added ccid and github id to team.txt

add ccid and github id to team.txt

---

app/src/main/java/com/T05/krowdtrialz/model/experiment/BinomialExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/CountExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/IntegerExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/MeasurementExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Trial.java
app/src/main/java/com/T05/krowdtrialz/model/location/Region.java
app/src/main/java/com/T05/krowdtrialz/model/scannable/Barcode.java
app/src/main/java/com/T05/krowdtrialz/model/scannable/QRCode.java
app/src/main/java/com/T05/krowdtrialz/model/user/User.java

This commit adds the following model classes
- Experiment
- MeasurementExperiment
- CountExperiment
- BinomialExperiment
- IntegerExperiment
Some methods can't be implemented yet because they depend on the implementation of the Trial class.
Also, I created stub classes for the classes that Experiment interacts with such as Region and QRCode.

Add experiment classes

---

app/src/main/java/com/T05/krowdtrialz/ui/User.java

added constructor and getters to user

Changed user model class

---

app/.idea/.gitignore
app/.idea/gradle.xml
app/.idea/misc.xml
app/.idea/modules.xml
app/.idea/vcs.xml
app/src/main/.idea/misc.xml
app/src/main/.idea/modules.xml
app/src/main/.idea/vcs.xml
app/src/main/.idea/workspace.xml
app/src/main/res/layout/activity_experiment_details_non_owner.xml
app/src/main/res/layout/activity_experiment_details_owner.xml

Added experiment details screen for both owner and non-owner.

Add experiment details screen

---

app/build.gradle
app/src/main/java/com/T05/krowdtrialz/MainActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/owner/OwnerFragment.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedFragment.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_owner.xml
app/src/main/res/layout/fragment_subscribed.xml
app/src/main/res/menu/bottom_nav_menu.xml
app/src/main/res/navigation/mobile_navigation.xml

- This PR fixes certain issues in the bottom nav fragments. 
- The app should now be able to build and run without errors, showing the basic layout with bottom navigation

fixing bottom nav

---

README
app/build.gradle
app/src/main/java/com/T05/krowdtrialz/model/experiment/BinomialExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/CountExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/IntegerExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/MeasurementExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/StatisticsExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Trial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/BinomialTrial.java
app/src/main/java/com/T05/krowdtrialz/util/Statistics.java

- Added the Apache Commons Math library for statistical methods
- Created a utility class called `Statistics` to act as a thin wrapper over the Apache library
- Created a class called `StatisticsExperiment` which is extended by `IntegerExperiment` and `MeasurementExperiment`

Implement statistics methods for Experiment subclasses

---

app/src/androidTest/java/com/T05/krowdtrialz/ExperimentDetailsOwnerActivityTest.java
app/src/main/java/com/T05/krowdtrialz/model/trial/IntegerTrial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/MeasurementTrial.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
app/src/main/res/layout/activity_experiment_details_owner.xml

- Currently cannot handle dates outside of 20xx

Implemented Method to show TimePlot and fixed method to show Histogram

---

app/src/main/java/com/T05/krowdtrialz/MainActivity.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/BinomialExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/CountExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/IntegerExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/MeasurementExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/StatisticsExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/interfaces/Tagged.java
app/src/main/java/com/T05/krowdtrialz/util/Database.java

- getTags must return Arraylist, but we convert to set & back to ArrayList, before returning to make sure there are no duplicates.

fixed addExperiments

---

app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/interfaces/Tagged.java

Revert "Functional search"

---

app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/interfaces/Tagged.java

Reverting this Revert since Functional Search was mostly added in pull request #77

Revert "Revert "Functional search""

---

app/build.gradle
app/src/main/java/com/T05/krowdtrialz/MainActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/search/SearchActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedViewModel.java
app/src/main/java/com/T05/krowdtrialz/util/Database.java
app/src/test/java/com/T05/krowdtrialz/DatabaseTest.java

Fix DataBase instantiation in SearchActivity. Fix tests, and also fix subscribed view model, but those changes are also in #90

Fix db in search and tests

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorList.java
app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorsActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedFragment.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedViewModel.java
app/src/main/java/com/T05/krowdtrialz/util/Database.java
app/src/main/res/layout/activity_contributors.xml
app/src/main/res/layout/activity_experiment_details_non_owner.xml
app/src/main/res/layout/activity_experiment_details_owner.xml
app/src/test/java/com/T05/krowdtrialz/ExperimentOwnerTest.java

This PR implements the following:
- Store a list of ignored user in each experiment
- Contributors screen UI
- some refactoring and minor changes in experiment details screens layouts
- some fixes in SubscribedViewModel class

Ignore Trials Functionality

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/T05/krowdtrialz/MainActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorsActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/search/SearchActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedFragment.java
app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedViewModel.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddBinomialTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddCountTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddIntegerTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddMeasurementTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/util/ExperimentList.java
app/src/main/res/layout/activity_add_binomial_trial.xml
app/src/main/res/layout/activity_add_count_trial.xml
app/src/main/res/layout/activity_add_integer_trial.xml
app/src/main/res/layout/activity_add_measurement_trial.xml

This PR implements these:
- Skeleton Activities for Add Trial screens 
- addTrial method in experiment details activities to start Add Trial activities.
- And OnClickListener in ExperimentList
If all looks good, these can probably be merged right away!

Add Trial Activities and ExperimentList

---

app/src/main/java/com/T05/krowdtrialz/model/experiment/BinomialExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/CountExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/IntegerExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/experiment/MeasurementExperiment.java
app/src/main/java/com/T05/krowdtrialz/model/trial/BinomialTrial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/CountTrial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/IntegerTrial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/MeasurementTrial.java
app/src/main/java/com/T05/krowdtrialz/model/trial/Trial.java
app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentPlots.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddBinomialTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddCountTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddIntegerTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddMeasurementTrialActivity.java

After partially refactoring the Database class we realized that our refactoring plan would not fix the no-argument constructor error so instead we used the following solution: store date and location as String dateCreated, int longitute, int latitude.

Fixed no argument constructor error 

---

app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentDetailsActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentMore.java
app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/LocationRequiredDialogFragment.java
app/src/main/res/layout/fragment_subscribed.xml

Show location required warning

---

app/src/main/java/com/T05/krowdtrialz/model/experiment/StatisticsExperiment.java
app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentPlots.java
app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentStatistics.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/AddBinomialTrialActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/TrialActivity.java
app/src/main/java/com/T05/krowdtrialz/util/Statistics.java
app/src/main/res/layout/activity_add_binomial_trial.xml
app/src/main/res/layout/activity_experiment_details.xml
app/src/main/res/layout/fragment_experiment_more.xml
app/src/main/res/layout/fragment_experiment_plots.xml
app/src/main/res/layout/fragment_experiment_statistics.xml
app/src/main/res/layout/fragment_subscribed.xml
app/src/main/res/values/strings.xml

- Improved the look of timeplot and histogram
- made the submit button of the add Trial screens return the user to the experiment details screen
- Fixed some minor formatting issues such as centering text on screen and preventing overlap of ui elements

Fixed some UI issues and fixed some statistics issues

---

app/src/androidTest/java/com/T05/krowdtrialz/StatisticsUITest.java

This PR includes Intent testing for US #13 and #12

Intent testing for statistics

---

app/src/main/res/layout/fragment_experiment_plots.xml

Get timeplot to show

---

app/src/main/java/com/T05/krowdtrialz/ui/experimentDetails/ExperimentDetailsActivity.java
app/src/main/java/com/T05/krowdtrialz/ui/trial/TrialActivity.java
app/src/main/java/com/T05/krowdtrialz/util/Database.java

This PR includes changes in the getExperimentByID that enable real-time database updated.

change getExperimentByID to use a snapshot listener

---

app/src/main/AndroidManifest.xml

This should be merged immediately, there were some fatal errors because I made a typo when fixing conflicts. This fixes those errors

fixed conflict issues

---

app/src/androidTest/java/com/T05/krowdtrialz/LocationIntentTests.java
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/fragment_publish.xml

Added the intent tests. Also fixed a few xml files so that there were no more overlapping views. Should be a pretty harmless PR and is ready for merge.

Intent test for US 06.02.01 and 06.04.01

---

app/src/main/java/com/T05/krowdtrialz/util/Database.java

Update experiments whenever owner changes

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorList.java
app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorsActivity.java
app/src/main/res/layout/activity_contributors.xml
app/src/main/res/layout/contributor_row.xml
app/src/main/res/values/colors.xml

An alternate getContributors method was created in the Experiments class. The issue seems to be resolved but could use some further testing to verify that the checkboxes are not misbehaving.

fix: contributors list

---

app/src/androidTest/java/com/T05/krowdtrialz/DatabaseTest.java
app/src/androidTest/java/com/T05/krowdtrialz/TrialIntentTests.java

The wrong user was being passed to db.getExperimentsByOwner() and this was causing the test to fail

Fix error in test case testGetExperimentsByOwner

---

app/src/main/java/com/T05/krowdtrialz/ui/QnA/AnswerViewModel.java
app/src/main/java/com/T05/krowdtrialz/ui/QnA/QuestionDetailsActivity.java

This is a better bandaid fix than just sending the user back to exp details in my opinion.

fixed by setting the position to the last position if it is -1

---

app/src/androidTest/java/com/T05/krowdtrialz/ExperimentIntentTests.java
app/src/androidTest/java/com/T05/krowdtrialz/LocationIntentTests.java
app/src/androidTest/java/com/T05/krowdtrialz/OwnerTests.java
app/src/androidTest/java/com/T05/krowdtrialz/QRCodeBarcodeIntentTests.java
app/src/androidTest/java/com/T05/krowdtrialz/QnATests.java
app/src/androidTest/java/com/T05/krowdtrialz/StatisticsUITest.java
app/src/androidTest/java/com/T05/krowdtrialz/TrialIntentTests.java

- Also click on new publish new experiment button

Update intent tests to use delete button instead of unpublish button
